logging:
  level:
    root: INFO
    org:
      example:
        springstudy: DEBUG

#H2 provide web based console that allows you to query and view db contents http://localhost:8080/h2-console
spring:
  datasource:
    url: jdbc:h2:mem:testdb #Use in memory database with name testdb
    driver-class-name: org.h2.Driver
    username: sa #Default Username
    password:  #No password set by default.
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update #Automatically update the db schema.
    show-sql: true #Show SQL queries in the log.

#Application Basic Auth.
  security:
    user:
      name: admin
      password: admin123